# Generated by Django 2.0.4 on 2018-06-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumid', models.IntegerField()),
                ('singerid', models.IntegerField()),
                ('albumname', models.CharField(max_length=255)),
                ('albumpic', models.CharField(max_length=255)),
                ('albumtime', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'album',
            },
        ),
    ]
