# Generated by Django 2.0.4 on 2018-06-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumId',
            new_name='AlbumItem',
        ),
    ]
