# Generated by Django 2.0.4 on 2018-06-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album_list', '0002_auto_20180605_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentId', models.IntegerField()),
                ('liked', models.IntegerField()),
                ('likedCount', models.IntegerField()),
                ('time', models.DateTimeField(max_length=255)),
                ('content', models.CharField(max_length=1000)),
                ('userId', models.IntegerField()),
                ('beReplied', models.IntegerField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='SingerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singerId', models.IntegerField()),
                ('zimu', models.IntegerField()),
                ('fenlei', models.IntegerField()),
                ('pic', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'singer',
            },
        ),
        migrations.CreateModel(
            name='SongCommentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songId', models.IntegerField()),
                ('commentId', models.IntegerField()),
            ],
            options={
                'db_table': 'song_coment',
            },
        ),
        migrations.CreateModel(
            name='SongItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songid', models.IntegerField()),
                ('albumid', models.IntegerField()),
                ('singerid', models.IntegerField()),
                ('length', models.CharField(max_length=255)),
                ('songname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'song',
            },
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('level', models.IntegerField()),
                ('dt', models.DateField()),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('sex', models.IntegerField()),
                ('event', models.IntegerField()),
                ('follows', models.IntegerField()),
                ('fans', models.IntegerField()),
                ('described', models.CharField(max_length=500)),
                ('weibo', models.CharField(max_length=255)),
                ('douban', models.CharField(max_length=255)),
                ('authStatus', models.IntegerField()),
                ('avatarUrl', models.CharField(max_length=255)),
                ('expertTags', models.CharField(max_length=45)),
                ('experts', models.CharField(max_length=45)),
                ('locationInfo', models.CharField(max_length=45)),
                ('remarkName', models.CharField(max_length=45)),
                ('userType', models.IntegerField()),
                ('vipType', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='songcommentitem',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_list.UserItem'),
        ),
    ]
